### ISSUE TITLE
Proposal for `takeuntil` method

### ISSUE THREAD

**Issue by jbriales** [nvie/itertools.js#824]
I was looking for a "takeuntil" method across existing utils,
and the closest I found was `takewhile`.

While `takewhile` "produces elements from the iterable as long as the predicate is true",
I'd expect `takeuntil` to "produce elements from the iterable as long as the predicate is true".

E.g.
```js
test('takeWhile', () => {
  expect([...takewhile([1, 2, -1, 3], x => x > 0)]).toStrictEqual([1, 2]);
});

test('takeuntil', () => {
  expect([...takeuntil([1, 2, -1, 3], x => x < 0)]).toStrictEqual([1, 2, -1]);
});
```

Would it make sense to add this function to the library?

I.e. having
```js
function* takeuntil(iterable, predicate) {
  for (const value of iterable) {
    yield value;
    if (predicate(value)) return;
  }
}
```
compared to
```js
export function* takewhile<T>(iterable: Iterable<T>, predicate: Predicate<T>): Iterable<T> {
    for (const value of iterable) {
        if (!predicate(value)) return;
        yield value;
    }
}
```

**Comment by nvie** [comment]
I can see the usefulness of a function like that, because using just `takewhile`, you always read past the item that breaks the predicate, and you lose that information. It may be useful to have a version that retains and returns the otherwise discarded value.

To me, `takeuntil` is not the best name for such function, though. I think `takeuntil(iterable, pred)` should always be equivalent to `takewhile(iterable, invert(pred))`. So `takewhile(numbers, isPositive)` would be the same as `takeuntil(numbers, isNegative)`.

Example:

```js
takewhile([2, 4, 6, -1, -2, -3], isPositive)  // [2, 4, 6]
takeuntil([2, 4, 6, -1, -2, -3], isNegative)  // also [2, 4, 6], not including the -1
```

The proposed implementation here is more like a `takewhileInclusive`. That said, I think that that is a useful function to add, so I'd be happy to merge it if you want to contribute that!

Thanks!

**Comment by nvie** [comment]
The reason I prefer a separate name like `takewhileInclusive` is that it has this behavior that may be surprising if not documented properly:

- For all items returned **except the last one**, the predicate will definitely hold
- For the **last item** returned, the predicate _could or could not_ hold (depending on whether it exhausted its input or not)

This means you will always have to do extra checking on the last element of the returned result when handling that… 🤔

**Comment by jbriales** [comment]
Great to hear! Fully agree on the naming. Better be explicit about it with the `Inclusive`.

A minor Q: Is there any style preference on having a separate function `takewhileInclusive` vs having an option in `takewhile` to define the "inclusive" behavior?
In fact, I think if we made it an option, as in `takewhile(iterable, predicate, {inclusive: true})`, it would lend itself to be always explicit on the inclusive-vs-non-inclusive behavior.

**Comment by nvie** [comment]
I'd quite like that 👍

**Comment by jbriales** [comment]
I still plan to make a pull request for this. Need to find some idle time in the coming weeks :)
